//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineHotelManagementSystemWebApplication.AddMenuServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddMenuServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMenuDDLWCF", ReplyAction="http://tempuri.org/IService1/AddMenuDDLWCFResponse")]
        EntityLayers.MenuTypes[] AddMenuDDLWCF();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMenuIns", ReplyAction="http://tempuri.org/IService1/AddMenuInsResponse")]
        int AddMenuIns(EntityLayers.Menu _menuObj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : OnlineHotelManagementSystemWebApplication.AddMenuServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<OnlineHotelManagementSystemWebApplication.AddMenuServiceReference.IService1>, OnlineHotelManagementSystemWebApplication.AddMenuServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EntityLayers.MenuTypes[] AddMenuDDLWCF() {
            return base.Channel.AddMenuDDLWCF();
        }
        
        public int AddMenuIns(EntityLayers.Menu _menuObj) {
            return base.Channel.AddMenuIns(_menuObj);
        }
    }
}
