//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineHotelManagementSystemWebApplication.DeleteMenuReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Menu", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Menu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int _menuIDField;
        
        private int _menuTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _menuDescriptionField;
        
        private decimal _menuPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _menuItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _menuID {
            get {
                return this._menuIDField;
            }
            set {
                if ((this._menuIDField.Equals(value) != true)) {
                    this._menuIDField = value;
                    this.RaisePropertyChanged("_menuID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _menuTypeID {
            get {
                return this._menuTypeIDField;
            }
            set {
                if ((this._menuTypeIDField.Equals(value) != true)) {
                    this._menuTypeIDField = value;
                    this.RaisePropertyChanged("_menuTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string _menuDescription {
            get {
                return this._menuDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this._menuDescriptionField, value) != true)) {
                    this._menuDescriptionField = value;
                    this.RaisePropertyChanged("_menuDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal _menuPrice {
            get {
                return this._menuPriceField;
            }
            set {
                if ((this._menuPriceField.Equals(value) != true)) {
                    this._menuPriceField = value;
                    this.RaisePropertyChanged("_menuPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string _menuItem {
            get {
                return this._menuItemField;
            }
            set {
                if ((object.ReferenceEquals(this._menuItemField, value) != true)) {
                    this._menuItemField = value;
                    this.RaisePropertyChanged("_menuItem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeleteMenuReference.DeleteMenuServiceSoap")]
    public interface DeleteMenuServiceSoap {
        
        // CODEGEN: Generating message contract since element name DeleteMenuListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMenuList", ReplyAction="*")]
        OnlineHotelManagementSystemWebApplication.DeleteMenuReference.DeleteMenuListResponse DeleteMenuList(OnlineHotelManagementSystemWebApplication.DeleteMenuReference.DeleteMenuListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMenu", ReplyAction="*")]
        void DeleteMenu(int MenuID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMenuListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMenuList", Namespace="http://tempuri.org/", Order=0)]
        public OnlineHotelManagementSystemWebApplication.DeleteMenuReference.DeleteMenuListRequestBody Body;
        
        public DeleteMenuListRequest() {
        }
        
        public DeleteMenuListRequest(OnlineHotelManagementSystemWebApplication.DeleteMenuReference.DeleteMenuListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteMenuListRequestBody {
        
        public DeleteMenuListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMenuListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMenuListResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineHotelManagementSystemWebApplication.DeleteMenuReference.DeleteMenuListResponseBody Body;
        
        public DeleteMenuListResponse() {
        }
        
        public DeleteMenuListResponse(OnlineHotelManagementSystemWebApplication.DeleteMenuReference.DeleteMenuListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteMenuListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OnlineHotelManagementSystemWebApplication.DeleteMenuReference.Menu[] DeleteMenuListResult;
        
        public DeleteMenuListResponseBody() {
        }
        
        public DeleteMenuListResponseBody(OnlineHotelManagementSystemWebApplication.DeleteMenuReference.Menu[] DeleteMenuListResult) {
            this.DeleteMenuListResult = DeleteMenuListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DeleteMenuServiceSoapChannel : OnlineHotelManagementSystemWebApplication.DeleteMenuReference.DeleteMenuServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteMenuServiceSoapClient : System.ServiceModel.ClientBase<OnlineHotelManagementSystemWebApplication.DeleteMenuReference.DeleteMenuServiceSoap>, OnlineHotelManagementSystemWebApplication.DeleteMenuReference.DeleteMenuServiceSoap {
        
        public DeleteMenuServiceSoapClient() {
        }
        
        public DeleteMenuServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeleteMenuServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeleteMenuServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeleteMenuServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineHotelManagementSystemWebApplication.DeleteMenuReference.DeleteMenuListResponse OnlineHotelManagementSystemWebApplication.DeleteMenuReference.DeleteMenuServiceSoap.DeleteMenuList(OnlineHotelManagementSystemWebApplication.DeleteMenuReference.DeleteMenuListRequest request) {
            return base.Channel.DeleteMenuList(request);
        }
        
        public OnlineHotelManagementSystemWebApplication.DeleteMenuReference.Menu[] DeleteMenuList() {
            OnlineHotelManagementSystemWebApplication.DeleteMenuReference.DeleteMenuListRequest inValue = new OnlineHotelManagementSystemWebApplication.DeleteMenuReference.DeleteMenuListRequest();
            inValue.Body = new OnlineHotelManagementSystemWebApplication.DeleteMenuReference.DeleteMenuListRequestBody();
            OnlineHotelManagementSystemWebApplication.DeleteMenuReference.DeleteMenuListResponse retVal = ((OnlineHotelManagementSystemWebApplication.DeleteMenuReference.DeleteMenuServiceSoap)(this)).DeleteMenuList(inValue);
            return retVal.Body.DeleteMenuListResult;
        }
        
        public void DeleteMenu(int MenuID) {
            base.Channel.DeleteMenu(MenuID);
        }
    }
}
