//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace OnlineHotelManagementSystemWebApplication
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PaymentHotelDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PaymentHotelDBEntities object using the connection string found in the 'PaymentHotelDBEntities' section of the application configuration file.
        /// </summary>
        public PaymentHotelDBEntities() : base("name=PaymentHotelDBEntities", "PaymentHotelDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PaymentHotelDBEntities object.
        /// </summary>
        public PaymentHotelDBEntities(string connectionString) : base(connectionString, "PaymentHotelDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PaymentHotelDBEntities object.
        /// </summary>
        public PaymentHotelDBEntities(EntityConnection connection) : base(connection, "PaymentHotelDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Payment> Payments
        {
            get
            {
                if ((_Payments == null))
                {
                    _Payments = base.CreateObjectSet<Payment>("Payments");
                }
                return _Payments;
            }
        }
        private ObjectSet<Payment> _Payments;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Payments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPayments(Payment payment)
        {
            base.AddObject("Payments", payment);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HotelDBPaymentModel", Name="Payment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Payment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Payment object.
        /// </summary>
        /// <param name="paymentID">Initial value of the PaymentID property.</param>
        /// <param name="dateOfPayment">Initial value of the DateOfPayment property.</param>
        /// <param name="paymentMode">Initial value of the PaymentMode property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        public static Payment CreatePayment(global::System.Int32 paymentID, global::System.DateTime dateOfPayment, global::System.String paymentMode, global::System.Decimal amount)
        {
            Payment payment = new Payment();
            payment.PaymentID = paymentID;
            payment.DateOfPayment = dateOfPayment;
            payment.PaymentMode = paymentMode;
            payment.Amount = amount;
            return payment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PaymentID
        {
            get
            {
                return _PaymentID;
            }
            set
            {
                if (_PaymentID != value)
                {
                    OnPaymentIDChanging(value);
                    ReportPropertyChanging("PaymentID");
                    _PaymentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PaymentID");
                    OnPaymentIDChanged();
                }
            }
        }
        private global::System.Int32 _PaymentID;
        partial void OnPaymentIDChanging(global::System.Int32 value);
        partial void OnPaymentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                OnOrderIDChanging(value);
                ReportPropertyChanging("OrderID");
                _OrderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderID");
                OnOrderIDChanged();
            }
        }
        private Nullable<global::System.Int32> _OrderID;
        partial void OnOrderIDChanging(Nullable<global::System.Int32> value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfPayment
        {
            get
            {
                return _DateOfPayment;
            }
            set
            {
                OnDateOfPaymentChanging(value);
                ReportPropertyChanging("DateOfPayment");
                _DateOfPayment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfPayment");
                OnDateOfPaymentChanged();
            }
        }
        private global::System.DateTime _DateOfPayment;
        partial void OnDateOfPaymentChanging(global::System.DateTime value);
        partial void OnDateOfPaymentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PaymentMode
        {
            get
            {
                return _PaymentMode;
            }
            set
            {
                OnPaymentModeChanging(value);
                ReportPropertyChanging("PaymentMode");
                _PaymentMode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PaymentMode");
                OnPaymentModeChanged();
            }
        }
        private global::System.String _PaymentMode;
        partial void OnPaymentModeChanging(global::System.String value);
        partial void OnPaymentModeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BankName
        {
            get
            {
                return _BankName;
            }
            set
            {
                OnBankNameChanging(value);
                ReportPropertyChanging("BankName");
                _BankName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BankName");
                OnBankNameChanged();
            }
        }
        private global::System.String _BankName;
        partial void OnBankNameChanging(global::System.String value);
        partial void OnBankNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CardType
        {
            get
            {
                return _CardType;
            }
            set
            {
                OnCardTypeChanging(value);
                ReportPropertyChanging("CardType");
                _CardType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CardType");
                OnCardTypeChanged();
            }
        }
        private global::System.String _CardType;
        partial void OnCardTypeChanging(global::System.String value);
        partial void OnCardTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CardNumber
        {
            get
            {
                return _CardNumber;
            }
            set
            {
                OnCardNumberChanging(value);
                ReportPropertyChanging("CardNumber");
                _CardNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CardNumber");
                OnCardNumberChanged();
            }
        }
        private global::System.String _CardNumber;
        partial void OnCardNumberChanging(global::System.String value);
        partial void OnCardNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NameOnCard
        {
            get
            {
                return _NameOnCard;
            }
            set
            {
                OnNameOnCardChanging(value);
                ReportPropertyChanging("NameOnCard");
                _NameOnCard = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NameOnCard");
                OnNameOnCardChanged();
            }
        }
        private global::System.String _NameOnCard;
        partial void OnNameOnCardChanging(global::System.String value);
        partial void OnNameOnCardChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();

        #endregion
    
    }

    #endregion
    
}
