<%@ Page Title="" Language="C#" MasterPageFile="~/UserInside.Master" AutoEventWireup="true" CodeBehind="UserOrderDetails.aspx.cs" Inherits="OnlineHotelManagementSystemWebApplication.WebForm20" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

<center> 
<h3> Your Order details are:</h3>
<br />
    <asp:GridView ID="gvOrderDetails" runat="server" BackColor="White" 
        BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" 
        ForeColor="Black" GridLines="Vertical" 
        AutoGenerateDeleteButton="True" 
        onrowdeleting="gvOrderDetails_RowDeleting">
        <AlternatingRowStyle BackColor="#CCCCCC" />
        <FooterStyle BackColor="#CCCCCC" />
        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="#808080" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#383838" />
    </asp:GridView>

    <asp:GridView ID="gvTotal" runat="server">
    </asp:GridView>

    <br />
    <br />
    <asp:HyperLink ID="hlnkChangeOrder" runat="server" 
        NavigateUrl="~/UserFoodOrder.aspx" Font-Bold="True" Font-Overline="False" 
        Font-Size="Large" ForeColor="Red">Edit Order</asp:HyperLink>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;<asp:Button 
        ID="btnConfirm" runat="server" ForeColor="Red" onclick="btnConfirm_Click" 
        Text="Confirm Order" />
    &nbsp;&nbsp;

</center>


</asp:Content>
